name: get-all-items-links

on:
  schedule:
    - cron: "0 5,17 * * *" # Runs at 5 AM and 5 PM UTC everyday

  workflow_dispatch: # Allows manual triggering via GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Replace with your specific Python version

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager pandas

      - name: Run xvfb
        run: |
          # Start xvfb
          sudo Xvfb :99 -ac &
          # Export display environment variable
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          wget https://chromedriver.storage.googleapis.com/$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip -o chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run scraper script
        run: python scraper/get-all-items-links.py

      - name: Commit and push if there are changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          # Add only new files in scraper/ or public/data/ folders
          git add scraper/* public/data/*

          # Commit only if there are changes
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update items links" && git pull --rebase && git push)
